language: node_js
os: linux
node_js:
  - "node"
  - "12"
  - "10"
jobs:
  include:
    - stage: test
      if: branch = master OR tag IS present
      install:
        - npm install
      script:
        - npm test
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        cleanup: true
        provider: npm
        email: backend.services@zippadd.com
        api_key:
          secure: "ivxQGZpAnpr0X3Po9XgCPROujCCggelrawGCZPZEAIM3TzHq5ZEgAPRVOHBkuuM46XqmTLpjmCSn124SQXz5a6HEEJggPcazVsK3MF4BOZApWMKvKXg8CgzYo6zHhr1WvvK4/Gy62mwzDL2mIancu9oJ0h4HjaZDIQMPJFSFKU8MGV2HaKttpYDdTXoxIejxPLPF5UvwDUdhTe+RIlkTlONxY7b3XI2yyZknm4mNGXo1XGQDMNSSsDdnl3MeaPMxVB4jKu19SJWVSgbK2pxGg2Vd/kXTjPA/jJ0H9Fz8AdVx8eEicH728MaWOaXTB8/MFdMgQ/dAPGpS8Unqfe8MvLNodRevp6l5vmB/DPU6Spv9PJ2wmKMil39pt7zlOXiGzLyYhoE7kfnVPhwXRVEaTfn1TF4fgSpnuJFlhhpzzP3Aln47FgDeS4AvU/Nv9I+OYqqdsXoCjtN/rJzObjTTdwHZNQeqiNiCctdtpunEdXcjK3BYPNbvybP3j7USuP57kzveILcmmNIOHKUkX0M9OEq1GFEruh17edpxeanb/eek1KMg7aDGYzkCwa9ltD2vCa0k71XwgsXGFL08PgA02F/YdyiynCtWRHQR/jPvYYg5rEqvnmGt7OT8TS5vLD6Pys1v7pxocnpCCDzs/olPyYkUoVUSNLO9vbT8UtzPi6o="
        on:
          tags: true
          repo: zippadd/cfn-custom-resource
          condition: $(git fetch origin master:master && git branch --contains $TRAVIS_TAG | grep '^[\*| ] master$')
