language: node_js
os: linux
node_js:
  - node
  - '12'
  - '10'
jobs:
  include:
    - stage: test
      if: branch = master OR tag IS present
      install:
        - npm install
      script:
        - npm test
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        cleanup: true
        provider: npm
        email: backend.services@zippadd.com
        api_key:
          secure: "fOErEfL2hRcxvpRVsTDwNF9pkxZ0+xdClWKlgHbfpM7Ynr073hVjlWAElEc++X7Ob27xL81EdN5S5v5aUVNdeEqoXnKROEASDXQwxHdg2HEkCbWoBi82kiMnd0FTTFOYWohIBKLSVnnTg3mQvW03L/7bQY1RHtLRKkQ2zuCSGjuYLBrmECywRIRDqRCiQY1I3UAav+rEGyXLPlFkhdIptH7jeB7AP0xZEMWFE/XyU2IZ5ae6GrnzZ8reB/J6Z0IzOh7p2p8HXojXqYaL0SMlGzavP6F9zu18QD4bUZTODYkk06BrgxHSDeUNNRBsfZ+5bYAbONih26CNRe3Ls/f2rvjvtTD++s0Hn2Y6frdBpglpUpR9ti1/5RXWAlBoW09WjNeq2Ucs2mkTHJkVgnp0NBPLJDAlJ1Jtk6X1Dhc9iV5Dwb8/xP+lnUN92dKlGaDYqsf3Vw+JfGjTsLh7zLkpc7V5wMDrwGZj5l8jYcys2YEdT7/xrXH+UOOqti/pF9geu+pyHJQfkEBxPYU99MMCIcV7ClxCmk0MHKk7WDDEUVFQh34gFPGDFJzDSeJV7pYdApChSERhZjRQ3QcwaHjIw/BJarc0eDdpPhqRZRUuGGZZv3z1YzgRkFD+M4o8dLX+GW1jWg9DE4DE4BlgDcuemqgv24IqKMrA5iGID9pGY0s="
        on:
          tags: true
          repo: zippadd/cfn-custom-resource
          condition: $(git fetch origin master:master && git branch --contains $TRAVIS_TAG | grep '^[\*| ] master$')
